//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleXML {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleXML() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebService.Tests.SampleXML", typeof(SampleXML).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soapenv:Envelope xmlns:ns=&quot;http://www.starstandard.org/STAR/5&quot; xmlns:ns1=&quot;http://www.openapplications.org/oagis/9&quot; xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:tran=&quot;http://www.starstandards.org/webservices/2005/10/transport&quot; xmlns:urn=&quot;urn:com.gm:vls&quot;&gt;{0}
        ///    &lt;soapenv:Body&gt;
        ///      &lt;tran:ProcessMessage&gt;
        ///        &lt;tran:payload xmlns:oagis=&quot;http://www.openapplications.org/oagis/9&quot; xmlns:star=&quot;http://www.starstandard.org/STAR/5&quot; xmlns:vls=&quot;urn:com.gm:vls&quot;&gt;
        ///          &lt;tran:content&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnvelopeTemplate {
            get {
                return ResourceManager.GetString("EnvelopeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;vls:ExtGetVehicleInventory xsi:schemaLocation=&quot;urn:com.gm:vls ExtGetVehicleInventory.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///            &lt;vls:ExtApplicationArea&gt;
        ///              &lt;vls:ExtSender&gt;
        ///                &lt;star:ComponentID&gt;Locate Module&lt;/star:ComponentID&gt;
        ///                &lt;star:TaskID&gt;Locate Vehicle&lt;/star:TaskID&gt;
        ///                &lt;star:CreatorNameCode&gt;ADP&lt;/star:CreatorNameCode&gt;
        ///                &lt;star:SenderNameCode&gt;AD&lt;/star:SenderNameCode&gt;
        ///                &lt;star:DealerNumberID&gt;119086&lt;/st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtGetVehicleInventory {
            get {
                return ResourceManager.GetString("ExtGetVehicleInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;vls:ExtGetVehicleInventory xmlns:star=&quot;http://www.starstandard.org/STAR/5&quot; xmlns:vls=&quot;urn:com.gm:vls&quot;&gt;
        ///  
        ///  &lt;vls:ExtApplicationArea&gt;
        ///    &lt;vls:ExtSender&gt;
        ///      &lt;star:ComponentID&gt;Locate Module&lt;/star:ComponentID&gt;
        ///      &lt;star:TaskID&gt;Locate Vehicle&lt;/star:TaskID&gt;
        ///      &lt;star:CreatorNameCode&gt;ADP&lt;/star:CreatorNameCode&gt;
        ///      &lt;star:SenderNameCode&gt;AD&lt;/star:SenderNameCode&gt;
        ///      &lt;star:DealerNumberID&gt;119086&lt;/star:DealerNumberID&gt;
        ///      &lt;vls:ExtDealerCountryCode&gt;US&lt;/vls:ExtDealerCountryCode&gt;
        ///      &lt;vls:ExtLanguageCode&gt;e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtGetVehicleInventoryMinimum {
            get {
                return ResourceManager.GetString("ExtGetVehicleInventoryMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ExtGetVehicleInventory xsi:schemaLocation=&quot;urn:com.gm:vls ExtGetVehicleInventory.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;ExtApplicationArea&gt;
        ///    &lt;ExtSender&gt;
        ///      &lt;ComponentID&gt;Locate Module&lt;/ComponentID&gt;
        ///      &lt;TaskID&gt;Locate Vehicle&lt;/TaskID&gt;
        ///      &lt;CreatorNameCode&gt;ADP&lt;/CreatorNameCode&gt;
        ///      &lt;SenderNameCode&gt;AD&lt;/SenderNameCode&gt;
        ///      &lt;DealerNumberID&gt;119086&lt;/DealerNumberID&gt;
        ///      &lt;ExtDealerCountryCode&gt;US&lt;/ExtDealerCountryCode&gt;
        ///      &lt;ExtLanguageCode&gt;en-US&lt;/ExtLanguageCode&gt;
        ///    &lt;/ExtSen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtGetVehicleInventoryNONamespace {
            get {
                return ResourceManager.GetString("ExtGetVehicleInventoryNONamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soapenv:Envelope xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:urn=&quot;urn:com.gm:vls&quot; xmlns:ns=&quot;http://www.starstandard.org/STAR/5&quot; xmlns:ns1=&quot;http://www.openapplications.org/oagis/9&quot; xmlns:starws=&quot;http://www.starstandards.org/webservices/2005/10/transport&quot;&gt;
        ///   &lt;soap:Header xmlns:wsse=&quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd&quot; xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:wsu=&quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wss [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllMakesEntireEnvelopeXML {
            get {
                return ResourceManager.GetString("GetAllMakesEntireEnvelopeXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;vls:ExtGetVehicleSpecifications xsi:schemaLocation=&quot;urn:com.gm:vls ExtGetVehicleSpecification.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///                  &lt;vls:ExtApplicationArea&gt;
        ///                     &lt;vls:ExtSender&gt;
        ///                        &lt;star:ComponentID&gt;Vehicle Selector Module&lt;/star:ComponentID&gt;
        ///                        &lt;star:TaskID&gt;Vehicle Selector&lt;/star:TaskID&gt;
        ///                        &lt;star:CreatorNameCode&gt;EASYDEAL&lt;/star:CreatorNameCode&gt;
        ///                        &lt;star:SenderNameCode&gt;Q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllYears {
            get {
                return ResourceManager.GetString("GetAllYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Sample XML file generated by XMLSpy v2012 rel. 2 sp1 (http://www.altova.com)--&gt;
        ///&lt;vls:ExtGetVehicleInventory xsi:schemaLocation=&quot;urn:com.gm:vls ExtGetVehicleInventory.xsd&quot; xmlns:oagis=&quot;http://www.openapplications.org/oagis/9&quot; xmlns:star=&quot;http://www.starstandard.org/STAR/5&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:vls=&quot;urn:com.gm:vls&quot;&gt;
        ///	&lt;vls:ExtApplicationArea&gt;
        ///		&lt;vls:ExtSender&gt;
        ///			&lt;star:ComponentID&gt;Locate Module&lt;/star:ComponentID&gt;
        ///			&lt;star:T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetVehicleInventoryWithAllCriteria {
            get {
                return ResourceManager.GetString("GetVehicleInventoryWithAllCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soap:Header xmlns:oagis=&quot;http://www.openapplications.org/oagis/9&quot; xmlns:starws=&quot;http://www.starstandards.org/webservices/2005/10/transport&quot; xmlns:wsa=&quot;http://www.w3.org/2005/08/addressing&quot; xmlns:vls=&quot;urn:com.gm:vls&quot; xmlns:star=&quot;http://www.starstandard.org/STAR/5&quot; xmlns:wsse=&quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd&quot; xmlns:wsu=&quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd&quot; xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;soapenv:Envelope xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;env:Body xmlns:env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:wsa=&quot;http://www.w3.org/2005/08/addressing&quot;&gt;
        ///    &lt;tran:ProcessMessageResponse xmlns:tran=&quot;http://www.starstandards.org/webservices/2005/10/transport&quot;&gt;
        ///      &lt;tran:payload&gt;
        ///        &lt;tran:content&gt;
        ///          &lt;inp1:ExtShowVehicleInventory xmlns:inp1=&quot;urn:com.gm:vls&quot; xmlns:ns99=&quot;http://www.example.org/vls&quot;&gt;
        ///            &lt;inp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InventorySearchResponse {
            get {
                return ResourceManager.GetString("InventorySearchResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Payload xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;content xmlns=&quot;http://www.starstandards.org/webservices/2005/10/transport&quot;&gt;
        ///&lt;vls:ExtGetVehicleInventory xsi:schemaLocation=&quot;urn:com.gm:vls ExtGetVehicleInventory.xsd&quot; xmlns:oagis=&quot;http://www.openapplications.org/oagis/9&quot; xmlns:star=&quot;http://www.starstandard.org/STAR/5&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:vls=&quot;urn:com.gm:vls&quot;&gt;
        ///	&lt;vls [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SerializedPayloadTemplate {
            get {
                return ResourceManager.GetString("SerializedPayloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soapenv:Envelope xmlns:ns=&quot;http://www.starstandard.org/STAR/5&quot; xmlns:ns1=&quot;http://www.openapplications.org/oagis/9&quot; xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:tran=&quot;http://www.starstandards.org/webservices/2005/10/transport&quot; xmlns:urn=&quot;urn:com.gm:vls&quot;&gt;
        ///   &lt;soap:Header xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:starws=&quot;http://www.starstandards.org/webservices/2005/10/transport&quot; xmlns:wsa=&quot;http://www.w3.org/2005/08/addressing&quot; xmlns:wsse=&quot;http://docs.oasis-open.org/wss/2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkingSOAPEnvelopeXML {
            get {
                return ResourceManager.GetString("WorkingSOAPEnvelopeXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soapenv:Envelope xmlns:ns=&quot;http://www.starstandard.org/STAR/5&quot; xmlns:ns1=&quot;http://www.openapplications.org/oagis/9&quot; xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:tran=&quot;http://www.starstandards.org/webservices/2005/10/transport&quot; xmlns:urn=&quot;urn:com.gm:vls&quot;&gt;
        ///  &lt;soap:Header xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:starws=&quot;http://www.starstandards.org/webservices/2005/10/transport&quot; xmlns:wsa=&quot;http://www.w3.org/2005/08/addressing&quot; xmlns:wsse=&quot;http://docs.oasis-open.org/wss/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkingSOAPEnvelopeXMLMinimum {
            get {
                return ResourceManager.GetString("WorkingSOAPEnvelopeXMLMinimum", resourceCulture);
            }
        }
    }
}
