using Data.Entities;
using ORM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Data.Repository
{
    /// <summary>
    /// this is an example of a thing that would need to be auto generated by a t4 template
    /// okay so what happens here, does this thing need to be hard coded to use the specific data store code like ado.net
    /// or does this thing use another thing that will dynamically determine that
    /// </summary>
    public class PersonRepository : IRepository<Person>
    {
        IQueryBuilder<BaseEntity> qb = null;

        public PersonRepository()
        {
            qb = new QueryBuilder<BaseEntity>(new Entity<BaseEntity>() { Name = "Person" });
        }

        public void Fill(List<Person> collection)
        {
            for (int i = 0; i < 1000; i++)
            {
                collection.Add(new Person() { FirstName = "Mike", LastName = i.ToString() });
                collection.Add(new Person() { FirstName = "Mike", LastName = "Smith" });
                collection.Add(new Person() { FirstName = "Mike", LastName = "Smith" });
                collection.Add(new Person() { FirstName = "Mike", LastName = "Smith" });
                collection.Add(new Person() { FirstName = "Mike", LastName = "Smith" });
                collection.Add(new Person() { FirstName = "Mike", LastName = "Smith" });
            }
        }
        public Person Get(int id)
        {
            return new Person();
        }
        public void Save(Person entity)
        {
            throw new NotImplementedException();
        }
    }
}
