using ORM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Data.Entities
{
    /// <summary>
    /// this is an example of an entity that would need to be auto generated by T4 template
    /// there is no point to having to make each one of these by hand
    /// </summary>
    public partial class Person : BaseEntity
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
    /// <summary>
    /// needs to be autogenerated
    /// this might be ackward 
    /// </summary>
    public partial class Person
    {
        public static class Fields
        {
            public static Field Id
            {
                get { return null; }
            }
            public static Field FirstName
            {
                get { return null; }
            }
        }
    }
    /// <summary>
    /// this might be ackward, how is the user supposed to know that the relations come from here
    /// </summary>
    public partial class Person
    {
        public class Relations
        {
            public static Relation Addresses
            {
                get { return null; }
            }
            public static Relation Emails
            {
                get { return null; }
            }

        }
    }
}
